"""Create location table

Revision ID: 51cc7ce89480
Revises: 
Create Date: 2025-10-26 03:50:11.760120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51cc7ce89480'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location',
    sa.Column('region', sa.String(length=50), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_location_district'), 'location', ['district'], unique=False)
    op.create_index(op.f('ix_location_id'), 'location', ['id'], unique=True)
    op.create_index(op.f('ix_location_region'), 'location', ['region'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_location_region'), table_name='location')
    op.drop_index(op.f('ix_location_id'), table_name='location')
    op.drop_index(op.f('ix_location_district'), table_name='location')
    op.drop_table('location')
    # ### end Alembic commands ###
