services:
  fastapi:
    build:
      context: .
      dockerfile: deploy/docker/Dockerfile.dev
    env_file:
      - deploy/env/.env.dev
    ports:
      - "${API_PORT:-8000}:${API_PORT:-8000}"
    depends_on:
      - db
    networks:
      - main-network
    profiles:
      - dev
    volumes:
      - .:/code
      - /code/venv

  db:
    image: postgres:latest
    container_name: postgres_db
    env_file:
      - deploy/env/.env.dev
    ports:
      - "${POSTGRES_PORT:-5432}:${POSTGRES_PORT:-5432}"
    networks:
      - main-network
    profiles:
      - dev

networks:
  main-network:
    driver: bridge
